#!/bin/bash

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
cd "$PROJECT_ROOT"

# Get list of staged frontend files (.js, .ts, .jsx, .tsx)
STAGED_FRONTEND_FILES=$(git diff --cached --name-only --relative frontend | grep -E '\.(js|ts|jsx|tsx)$' || true)

# Format staged frontend files with Prettier and re-stage formatted files
if [ -n "$STAGED_FRONTEND_FILES" ]; then
    npx prettier --write $STAGED_FRONTEND_FILES
    git add $STAGED_FRONTEND_FILES
fi

# Get list of staged backend files (.java)
STAGED_BACKEND_FILES=$(git diff --cached --name-only --relative backend | grep -E '\.java$' || true)

# Format staged backend files with Spotless and re-stage formatted files
if [ -n "$STAGED_BACKEND_FILES" ]; then
    cd backend
    ./gradlew spotlessApply
    cd "$PROJECT_ROOT"

    for file in $STAGED_BACKEND_FILES; do
        git add "$file"
    done
fi